//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/querySql", ReplyAction="http://tempuri.org/IService/querySqlResponse")]
        WindowsFormsApplication1.ServiceReference1.querySqlResponse querySql(WindowsFormsApplication1.ServiceReference1.querySqlRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/querySql", ReplyAction="http://tempuri.org/IService/querySqlResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.querySqlResponse> querySqlAsync(WindowsFormsApplication1.ServiceReference1.querySqlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="querySql", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class querySqlRequest {
        
        public querySqlRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="querySqlResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class querySqlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet querySqlResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool queryParam;
        
        public querySqlResponse() {
        }
        
        public querySqlResponse(System.Data.DataSet querySqlResult, bool queryParam) {
            this.querySqlResult = querySqlResult;
            this.queryParam = queryParam;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WindowsFormsApplication1.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.IService>, WindowsFormsApplication1.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.querySqlResponse WindowsFormsApplication1.ServiceReference1.IService.querySql(WindowsFormsApplication1.ServiceReference1.querySqlRequest request) {
            return base.Channel.querySql(request);
        }
        
        public System.Data.DataSet querySql(out bool queryParam) {
            WindowsFormsApplication1.ServiceReference1.querySqlRequest inValue = new WindowsFormsApplication1.ServiceReference1.querySqlRequest();
            WindowsFormsApplication1.ServiceReference1.querySqlResponse retVal = ((WindowsFormsApplication1.ServiceReference1.IService)(this)).querySql(inValue);
            queryParam = retVal.queryParam;
            return retVal.querySqlResult;
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.querySqlResponse> querySqlAsync(WindowsFormsApplication1.ServiceReference1.querySqlRequest request) {
            return base.Channel.querySqlAsync(request);
        }
    }
}
